In [2]:
import numpy as np

In [2]:
#Q1 Create Null vector size of 10 whihch 5th value is 1

In [3]:
null_array=np.zeros(10)
null_array[4]=1
null_array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [13]:
#Q2 Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg 
# of the array

In [12]:
a=int(input('Enter your a value: '))
b=int(input('Enter your b value: '))

random_array=np.random.randn(a,b)
print(random_array)

avg_mean=np.mean(random_array)
print(f'The average mean is: {avg_mean}')

Enter your a value: 32
Enter your b value: 100
[[ 0.04725428  1.26711086 -0.52729721 ... -0.37561816 -0.72695507
  -1.05815159]
 [-0.13866308 -0.20705416  0.99643914 ...  0.64816216  0.56416144
   1.20686835]
 [ 1.38005652  1.4284668  -0.32921306 ...  0.51127501  1.67186331
   0.06005022]
 ...
 [ 0.22157639 -1.19828288  0.58343617 ...  0.31504949 -0.16839819
  -0.90068562]
 [-0.18338454  1.00533586 -1.42403014 ...  0.04990271  2.00418505
  -0.99779643]
 [-0.34847585  1.20109919 -2.81640075 ... -0.63234277  1.68400854
  -1.6602813 ]]
The average mean is: 0.00969906777965993


In [18]:
np.array([[1,1,1,1],[1,0,0,1],[1,0,0,1],[1,1,1,1]])

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

In [29]:
np.zeros([4,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [78]:
# Q-3Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to 
# function.

import numpy as np
def create_array(a,b):    
    array=np.zeros([a,b],dtype=int)
    array[0,:]=1 #top row 
    array[:,0]=1 #left column
    array[:,-1]=1 #right column
    array[-1,:]=1  #bottom row
    return array
    
a=int(input('Enter your a value'))
b=int(input('Enter your b value'))
array=create_array(a,b)

print(array)

Enter your a value3
Enter your b value4
[[1 1 1 1]
 [1 0 0 1]
 [1 1 1 1]]


In [88]:
# Q-4 Create a vector of size 10 with values ranging from 0 to 1, both excluded.
vector= np.linspace(0,1,10)
print(vector)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [100]:
# Q-5 Can you create a identity mattrix of shape (3,4). If yes write code for it.
identity_matrix=np.eye(3,4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [107]:
np.linspace(0,4,25).reshape(5,5)

array([[0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667],
       [0.83333333, 1.        , 1.16666667, 1.33333333, 1.5       ],
       [1.66666667, 1.83333333, 2.        , 2.16666667, 2.33333333],
       [2.5       , 2.66666667, 2.83333333, 3.        , 3.16666667],
       [3.33333333, 3.5       , 3.66666667, 3.83333333, 4.        ]])

In [115]:
np.arange(5).reshape(5,1)+np.arange(5)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [116]:
# Q-6: Create a 5x5 matrix with row values ranging from 0 to 4.

matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [2]:
#Q-7: Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, and coordinates of a 
# point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance 
# array should be interger type.??

import numpy as np

random_vector= np.random.randint(1,101,size=(10,2))
given_point=np.array([10,2])

#Calculate the Euclidean for given and random point
distance=np.linalg.norm(random_vector-given_point,axis=1)

distance=distance.astype(int)

In [26]:
my_array=np.array([[1,2,3],[2,3,4],[5,6,7]])

In [27]:
my_array.size

9

In [ ]:
#Q8. You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.
import numpy as np

# Input: A single line of space-separated numbers
input_numbers = input("Enter space-separated numbers: ")

# Convert the input to a NumPy array
original_array = np.array([float(x) for x in input_numbers.split()])

# Reverse the array
reversed_array = np.flip(original_array)

# Print the reversed array with the element type float
print("Reversed NumPy array with type float:")
print(reversed_array.astype(float))